#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          getpart
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop (serial) particle counter readings
### END INIT INFO
#
# getpart		This init.d script is used to start serial particle counter readings.

ENV="env -i LANG=C PATH=/usr/local/bin:/usr/bin:/bin"
CONF=/etc/dlogger.conf
PART=part/getpart1.sh

set -e
. /lib/lsb/init-functions
. $CONF

if [ ! -x $BASE/$PART ]
then
	echo "No $PART installed"
	exit 0
fi

case $1 in
	start)
		log_daemon_msg "Starting serial particle counter client" "$PART"
		echo
		[ -f /screenlog.0 ] && cp /screenlog.0 $BASE/log/`date '+%Y-%m-%d_%H:%M'`.log
		screen -L -d -m $BASE/$PART
	;;
	stop)
		log_daemon_msg "Stopping serial particle counter client" "$PART"
		echo
		killall $PART 2>/dev/null
	;;
	*)
		log_success_msg "Usage: /etc/init.d/getpart {start|stop}"
		exit 1
	;;
esac
