#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          getgps
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Obtain gps readings
### END INIT INFO
#
# getgps		This init.d script is used to read the ADXL345 gps axes
#			It just calls ~pi/work/dlogger/getgps1.sh

ENV="env -i LANG=C PATH=/usr/local/bin:/usr/bin:/bin"
CONF=/etc/dlogger.conf
GC=gpis/getgps1.sh

set -e
. /lib/lsb/init-functions
. $CONF

if [ ! -x $BASE/$GC ]
then
	echo "No $GC installed"
	exit 0
fi

case $1 in
	start)
		log_daemon_msg "Starting gps reader" "$GC"
		echo
		mkdir -p $BASE/log
		[ -f /screenlog.0 ] && cp /screenlog.0 $BASE/log/`date '+%Y-%m-%d_%H:%M'`.log
		screen -L -d -m $BASE/$GC
	;;
	stop)
		log_daemon_msg "Stopping gps reader" "$GC"
		echo
		killall $GC 2>/dev/null
	;;
	*)
		log_success_msg "Usage: /etc/init.d/getgps {start|stop}"
		exit 1
	;;
esac
