#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          getpressure
# Required-Start:    $local_fs $remote_fs $syslog mysql
# Required-Stop:     $local_fs $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop pressure reader
### END INIT INFO
#
# getpressure		This init.d script is used to start pressure readings.
#set -x

ENV="env -i LANG=C PATH=/usr/local/bin:/usr/bin:/bin"
CONF=/etc/dlogger.conf
DUST=pressure/getpressure1.py

#ARGS="-m table"
ARGS="-m mysql"

set -e
. /lib/lsb/init-functions
. $CONF
export DB US PASS

if [ ! -x $BASE/$DUST ]
then
	echo "No $DUST installed"
	exit 0
fi

case $1 in
	start)
		log_daemon_msg "Starting pressure reader client" "$DUST"
		echo
		[ -f /screenlog.0 ] && cp /screenlog.0 $BASE/log/`date '+%Y-%m-%d_%H:%M'`.log
		screen -L -d -m $BASE/$DUST $ARGS
	;;
	stop)
		log_daemon_msg "Stopping pressure reader client" "$DUST"
		echo
        D=`basename $DUST`
#		killall $D 2>/dev/null
        kill `ps -ef | grep SCREEN | grep $D | awk '{print $2}'` 2>/dev/null
	;;
	*)
		log_success_msg "Usage: /etc/init.d/getpressure {start|stop}"
		exit 1
	;;
esac
