#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          getencoder
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop (serial) geiger counter readings
### END INIT INFO
#
# getencoder		This init.d script is used to read HEDSS encoder counters

ENV="env -i LANG=C PATH=/usr/local/bin:/usr/bin:/bin"
CONF=/etc/dlogger.conf

set -e
. /lib/lsb/init-functions
. $CONF

GS=$SENSORS/encoder/driver2/Default/encoder2
GC=$SENSORS/encoder/getencoder1.sh

if [ ! -x $GS ]
then
	echo "No $GS installed"
	exit 0
fi

if [ ! -x $GC ]
then
	echo "No $GC installed"
	exit 0
fi

case $1 in
	start)
		log_daemon_msg "Starting encoder server" "$GS"
		rm -f /var/run/pigpio.pid
		screen -d -m $GS
		sleep 1
		log_daemon_msg "Starting encoder reader" "$GC"
		echo
		screen -d -m $GC
	;;
	stop)
		log_daemon_msg "Stopping encoder reader and server" "$GC"
		echo
		killall `basename $GC` `basename $GS` 2>/dev/null
		rm -f /var/run/pigpio.pid
	;;
	*)
		log_success_msg "Usage: /etc/init.d/getencoder {start|stop}"
		exit 1
	;;
esac
