#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          getencoder
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop (serial) geiger counter readings
### END INIT INFO
#
# getencoder		This init.d script is used to read HEDSS encoder counters

ENV="env -i LANG=C PATH=/usr/local/bin:/usr/bin:/bin"
CONF=/etc/dlogger.conf
GC=encoder/getencoder1.sh

set -e
. /lib/lsb/init-functions
. $CONF

if [ ! -x $BASE/$GC ]
then
	echo "No $GC installed"
	exit 0
fi

case $1 in
	start)
		log_daemon_msg "Starting encoder reader" "$GC"
		echo
		screen -L -d -m $BASE/$GC
	;;
	stop)
		log_daemon_msg "Stopping encoder reader" "$GC"
		echo
		killall `basename $GC` 2>/dev/null
	;;
	*)
		log_success_msg "Usage: /etc/init.d/getencoder {start|stop}"
		exit 1
	;;
esac
